name: Sync Fork

on:
  schedule:
    - cron: '0 */2 * * *' # every 2 hours

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - id: sync
        uses: jiyeme/fork-news@v1.0.1
        with:
          user-name: ${{ github.actor }}
          user-email: jiyecafe@gmail.com
          from-branch: main
          to-branch: main
          access-token: ${{ secrets.GITHUB_TOKEN }}

      # ############# API ###############
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        if: steps.sync.outputs.has_new_commits == 'true'
        with:
          fetch-depth: 0

      - name: Copy Script
        if: steps.sync.outputs.has_new_commits == 'true'
        run: |
          git checkout sync
          mkdir -p dist/scripts
          cp ./.github/scripts/dir2json.js ./dist/scripts/dir2json.js
          git checkout main

      - name: Use Node.js ${{ matrix.node-version }}
        if: steps.sync.outputs.has_new_commits == 'true'
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Generate Tree Of Files
        if: steps.sync.outputs.has_new_commits == 'true'
        run: node ./dist/scripts/dir2json.js

      - name: Deploy to GitHub Pages
        if: steps.sync.outputs.has_new_commits == 'true'
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: api
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
