name: Test

on:
  push:
    branches: [sync]
  
jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      # REQUIRED step
      # Step 1: run a standard checkout action, provided by github
      - name: Checkout target repo
        uses: actions/checkout@v2
        with:
          # optional: set the branch to checkout,
          # sync action checks out your 'target_sync_branch' anyway
          ref:  main
          # REQUIRED if your upstream repo is private (see wiki)
          persist-credentials: false

      # REQUIRED step
      # Step 2: run the sync action
      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.0
        with:
          target_sync_branch: main
          # REQUIRED 'target_repo_token' exactly like this!
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_branch: main
          upstream_sync_repo: andream7/cuit_sharing
          upstream_pull_args: --allow-unrelated-histories
          # Set test_mode true to run tests instead of the true action!!
          test_mode: true
          git_config_user: 'jiyeme'
          git_config_email: 'jiyecafe@gmail.com'

      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
